# Generated by Django 5.2 on 2025-05-13 08:04

import django.db.models.deletion
import django_multitenant.mixins
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_seed_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDeviceOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(default=True, help_text='Is this device ready for use?')),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True)),
                ('valid_until', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, django_multitenant.mixins.TenantModelMixin),
        ),
    ]
