# Generated by Django 5.2 on 2025-05-03 15:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0003_alter_tenantuser_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantuser',
            name='phonenumber',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+\\d{9,15}$')]),
        ),
    ]
