# Generated by Django 5.2 on 2025-05-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_seed_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantuser',
            name='phonenumber_verified',
            field=models.BooleanField(default=False),
        ),
    ]
