# Generated by Django 5.2 on 2025-05-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0004_alter_tenantuser_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantuser',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
