# Generated by Django 5.2 on 2025-05-07 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0005_tenantuser_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='tenantuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='tenantuser',
            name='last_name',
        ),
    ]
