# Generated by Django 5.2 on 2025-05-28 22:07

import django.db.models.deletion
import django_multitenant.mixins
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0005_tenantuser_phonenumber_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=False)),
                ('tenant_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_state', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
        ),
    ]
