# Generated by Django 5.2 on 2025-05-08 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_seed_initial_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenantuser',
            old_name='location',
            new_name='address',
        ),
    ]
