# Generated by Django 5.2 on 2025-05-28 23:25

import django.db.models.deletion
import django_multitenant.mixins
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0006_automationstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationScript',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('script_name', models.CharField(max_length=255)),
                ('script_code', models.TextField()),
                ('tenant_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_scripts', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
        ),
    ]
