# Generated by Django 5.2 on 2025-05-08 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0006_remove_tenantuser_email_remove_tenantuser_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenantuser',
            old_name='location',
            new_name='address',
        ),
    ]
