# Generated by Django 5.2 on 2025-05-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0006_staffgroup_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('regular', 'regular'), ('admin', 'admin')], default=('regular', 'regular'), max_length=12),
        ),
        migrations.DeleteModel(
            name='StaffGroup',
        ),
    ]
